pipeline {
    agent any
    environment {
        GIT_REPO = 'git@github.com:iphilpot/testing_jenkins.git'
        CREDENTIALSID = 'JenkinsSSH'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building'
                sh '''
                    $DIFF=$(git diff --name-only $GIT_PREVIOUS_COMMIT $GIT_COMMIT)
                    awk '{print $1}' $DIFF
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}

def sparseCheckout() {
  def scmVars = checkout scm
  def commitHash = scmVars.GIT_COMMIT
  
  checkout scm: [
    $class: 'GitSCM', 
    branches: [[name: commitHash]], 
    doGenerateSubmoduleConfigurations: false, 
    extensions: [[
      $class: 'SparseCheckoutPaths', 
      sparseCheckoutPaths: [[
        path: 'bar'
      ]]
    ]], 
      submoduleCfg: [], 
      userRemoteConfigs: [[
        credentialsId: "${CREDENTIALSID}", 
        url: "${GIT_REPO}"
      ]]
  ]
}
